namespace SpriteKind {
    export const Boss = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    if (Random == 0) {
        game.showLongText("Fact 1/10. The Antarctic Treaty of 1959 makes it illegal to harm, or in any way interfere with, a penguin or its eggs.", DialogLayout.Full)
        game.gameOver(false)
    } else if (Random == 1) {
        game.showLongText("Fact 2/10. The Westren Australian colony of Little Penguins has been reduced by 90% in the last 20 years.", DialogLayout.Full)
        game.gameOver(false)
    } else if (Random == 2) {
        game.showLongText("Fact 3/10. Each year at least 50 little penguins get tangled in littered fishing nets.", DialogLayout.Full)
        game.gameOver(false)
    } else if (Random == 3) {
        game.showLongText("Fact 4/10. Due to introduced dogs and cats,15 little penguins die each night to attacks by wild cats and dogs.", DialogLayout.Full)
        game.gameOver(false)
    } else if (Random == 4) {
        game.showLongText("Fact 5/10.Due to the increased frequency of drought and extreme temperatures in Southern Australia has led to an increased fire risk. And these fires stop Little Penguins from nesting or emerging during daylight hours.", DialogLayout.Full)
        game.gameOver(false)
    } else {
        game.gameOver(false)
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (Random == 0) {
        game.showLongText("Fact 6/10. In 2011, 380 little penguins had to be relocated due to one oil spill.", DialogLayout.Full)
        game.gameOver(false)
    } else if (Random == 1) {
        game.showLongText("Fact 7/10. Due to artificial lights being left on a night, Little Penguins lose their sense of direction and struggle to find their nests", DialogLayout.Full)
        game.gameOver(false)
    } else if (Random == 2) {
        game.showLongText("Fact 8/10. Climate change is altering ocean conditions and food availability, making it harder for penguins to find prey. ", DialogLayout.Full)
        game.gameOver(false)
    } else if (Random == 3) {
        game.showLongText("Fact 9/10.Boats and watercraft can strike penguins at sea, causing injuries or death in some colonies.", DialogLayout.Full)
        game.gameOver(false)
    } else if (Random == 4) {
        game.showLongText("Fact 10/10. Introduced predators such as foxes, cats, dogs, rats, ferrets and stoats regularly attack little penguins, especially eggs and chicks in their nests.", DialogLayout.Full)
        game.gameOver(false)
    } else {
        game.gameOver(false)
    }
})
let projectile: Sprite = null
let Random = 0
game.showLongText("Everyday Little Penguins face a multitude of issues. From littering to oil spills. Many factors affect their daily lives of searching for food. So today, you'll play as a little penguin and experience a few of theses factors. ", DialogLayout.Full)
timer.after(30000, function () {
    Diffculty += 0.5
    timer.after(60000, function () {
        Diffculty += 0.5
        timer.after(90000, function () {
            game.gameOver(true)
        })
    })
})
Random = randint(0, 5)
info.setScore(0)
scene.setBackgroundImage(assets.image`myImage`)
let Diffculty = 1
let Penguin = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . f . . . 
    . . . . . . . . . . . . f . f . 
    . . . . . . . . . . . f f f f . 
    . . . . . . . . . . f f f f f f 
    . . . f f f . f f f f f f f 1 f 
    . . f f f f f f f f f f f 1 1 f 
    . f f 1 1 f f f f f f f f 1 1 1 
    4 f 1 f 1 1 f 1 f f f f 1 1 1 1 
    . f 1 1 1 f f 1 1 1 1 1 1 1 1 4 
    . . f f f f f 1 1 1 1 1 1 1 1 4 
    . . . . . . . . 1 1 1 1 1 1 . 4 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Penguin, 100, 100)
let Bottle_1 = sprites.create(assets.image`Bottle 1`, SpriteKind.Enemy)
let Bottle_2 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .....7977777777.....
    .....7777777777.....
    ......66666666......
    ......99999999......
    .....9999999999.....
    .....9999999999.....
    .....9999999999.....
    .....7777777777.....
    .....7777777777.....
    .....7777777776.....
    .....7777777776.....
    ......76666666......
    ....................
    ....................
    `, SpriteKind.Enemy)
let Bottle_3 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ........4eee........
    .......eeeeee.......
    .........cc.........
    .........4c.........
    ........4444........
    .......444444.......
    ......44444444......
    .....4444444444.....
    .....eeeeeeeeee.....
    .....eeeeeeeecc.....
    ......eeeeeecc......
    .......eccccc.......
    ....................
    ....................
    `, SpriteKind.Enemy)
let Bottle_4 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ........dd55........
    ........5555........
    .........44.........
    ........dddd........
    ........dddd........
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    ........dddd........
    ........4444........
    ....................
    `, SpriteKind.Enemy)
let Bottle_5 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ...e..e....e...e....
    ...e..e....e...e...e
    ...ee.ee..eee.ee...e
    ..eee.eeeeeee.eee.ee
    ..eeeeeeeeeeee44eeee
    .eeeeeeeeee444fff4ee
    eeeeeee4444fffffff4e
    eeee444ffffffff444ee
    .e44fffffff44444eeee
    ..ee44f444444eeeee..
    ...eee444eeeeee.....
    `, SpriteKind.Enemy)
Bottle_1.setPosition(randint(5, 160), 0)
Bottle_1.setVelocity(0, randint(1, 100))
Bottle_2.setPosition(randint(5, 160), 0)
Bottle_2.setVelocity(0, randint(50, 100))
Bottle_3.setPosition(randint(5, 160), 0)
Bottle_3.setVelocity(0, randint(50, 100))
Bottle_4.setVelocity(0, randint(50, 100))
Bottle_4.setPosition(randint(5, 160), 0)
Bottle_5.setVelocity(0, randint(50, 100))
Bottle_5.setPosition(randint(5, 160), 0)
game.onUpdateInterval(5000, function () {
    projectile = sprites.createProjectileFromSide(img`
        ..............fffcc.............
        ..............fcbddcc...........
        ...............fbbddcc..........
        ...............fcbbccf..........
        ..ccc.........ffccccccfffff.....
        ..cbbcc....fffcbbbbcbbbbbbbff...
        ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
        ...fbbdcfcccccbbbcbcbbffbbbbbbff
        ....fbbffcccccbbbbbcb1ff11bbbcbf
        ....fcbbcccccccbbbbb11111111bbbf
        ....fcccccccccccbbbb11cc33111bf.
        ...fcbbffbdbcccccbbb111c13cccf..
        ...fbbf..ccddddcfbbbc111c31cf...
        ..fbbf.....ccdccbbdbf111cccf....
        ..fff........ccbbdcfcccc........
        ..............fffff.............
        `, randint(50, 100) * Diffculty, 0)
    projectile.setPosition(0, Penguin.y)
    animation.runImageAnimation(
    projectile,
    [img`
        ..............fffcc.............
        ..............fcbddcc...........
        ...............fbbddcc..........
        ...............fcbbccf..........
        ..ccc.........ffccccccfffff.....
        ..cbbcc....fffcbbbbcbbbbbbbff...
        ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
        ...fbbdcfcccccbbbcbcbbffbbbbbbff
        ....fbbffcccccbbbbbcb1ff11bbbcbf
        ....fcbbcccccccbbbbb11111111bbbf
        ....fcccccccccccbbbb11cc33111bf.
        ...fcbbffbdbcccccbbb111c13cccf..
        ...fbbf..ccddddcfbbbc111c31cf...
        ..fbbf.....ccdccbbdbf111cccf....
        ..fff........ccbbdcfcccc........
        ..............fffff.............
        `,img`
        ..............fffcc.............
        ..............fbbddc............
        ...............fbbddc...........
        ccc............fcbbccf..........
        cbbcc.........ffccccccffffff....
        .cbbdc.....fffcbbbbbbbbbbbbbff..
        .fbbddc..ffcccbbbbcbcbbbbbbbbbff
        ..fbbdfffcccccbbbcbcbbffbbbbbcbf
        ..fcbbbcccccccbbbcbcb1ff1111bbbf
        ..fccbcccccccccbbbbbb11111111bf.
        .fcbbfffccccccccbbbb11cc33cccf..
        .fbbf...cbdbcccccbbb111c131cf...
        fbbf.....ccdddddfbbbc111c33f....
        fff........ccddfbbdbf1111ff.....
        .............cfbbdbfccccc.......
        ..............fffff.............
        `,img`
        ..............fffc..............
        ..............fbddcc............
        ..ccc.........ffbddbc...........
        ..cbbc.........fcbbccf..........
        ...cbdc.......ffccccccfffffff...
        ...fbdc....fffcbbbbbbbbbbbbbcff.
        ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
        ....fcdffcccccbbbcbcbbbffbbbbcbf
        ....fcbbccccccbbbcbcbbbff1111bbf
        ...fcbbccccccccbbbcbb11111111bf.
        ...fbbfffcccccccbbbb11bc33cccf..
        ..fbbf..cbdbcccccbbb111c131cf...
        ..fff....cbdddddccbbc111c33f....
        ..........ccbddccbbdf1111ff.....
        ............ccfbbbdfccccc.......
        ..............fffff.............
        `,img`
        ..............fffcc.............
        ..............fbbddc............
        ...............fbbddc...........
        ccc............fcbbccf..........
        cbbcc.........ffccccccffffff....
        .cbbdc.....fffcbbbbbbbbbbbbbff..
        .fbbddc..ffcccbbbbcbcbbbbbbbbbff
        ..fbbdfffcccccbbbcbcbbffbbbbbcbf
        ..fcbbbcccccccbbbcbcb1ff1111bbbf
        ..fccbcccccccccbbbbbb11111111bf.
        .fcbbfffccccccccbbbb11cc33cccf..
        .fbbf...cbdbcccccbbb111c131cf...
        fbbf.....ccdddddfbbbc111c33f....
        fff........ccddfbbdbf1111ff.....
        .............cfbbdbfccccc.......
        ..............fffff.............
        `],
    150,
    true
    )
})
forever(function () {
    if (Penguin.x > 160) {
        game.gameOver(false)
    }
    if (Penguin.y > 120) {
        game.gameOver(false)
    }
})
game.onUpdateInterval(100, function () {
    if (Bottle_1.y > 120) {
        Bottle_1.setPosition(randint(0, 160), 0)
        Bottle_1.setVelocity(0, randint(50, 100) * Diffculty)
        info.changeScoreBy(1)
    }
    if (Bottle_2.y > 120) {
        Bottle_2.setPosition(randint(0, 160), 0)
        Bottle_2.setVelocity(0, randint(50, 100) * Diffculty)
        info.changeScoreBy(1)
    }
    if (Bottle_3.y > 120) {
        Bottle_3.setPosition(randint(0, 160), 0)
        Bottle_3.setVelocity(0, randint(50, 100) * Diffculty)
        info.changeScoreBy(1)
    }
    if (Bottle_4.y > 120) {
        Bottle_4.setPosition(randint(0, 160), 0)
        Bottle_4.setVelocity(0, randint(50, 100) * Diffculty)
        info.changeScoreBy(1)
    }
    if (Bottle_5.y > 120) {
        Bottle_5.setPosition(randint(0, 160), 0)
        Bottle_5.setVelocity(0, randint(50, 100) * Diffculty)
        info.changeScoreBy(1)
    }
})
