namespace SpriteKind {
    export const Boss = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    if (Random == 0) {
        game.setGameOverMessage(false, "0")
    } else if (Random == 1) {
        game.setGameOverMessage(false, "1")
    } else if (Random == 2) {
        game.setGameOverMessage(false, "2")
    } else if (Random == 3) {
        game.setGameOverMessage(false, "3")
    } else if (Random == 4) {
        game.setGameOverMessage(false, "4")
    } else if (Random == 5) {
        game.setGameOverMessage(false, "5")
    } else if (Random == 6) {
        game.setGameOverMessage(false, "6")
    } else if (Random == 7) {
        game.setGameOverMessage(false, "7")
    } else if (Random == 8) {
        game.setGameOverMessage(false, "8")
    } else if (Random == 9) {
        game.setGameOverMessage(false, "9")
    } else if (Random == 10) {
        game.setGameOverMessage(false, "10")
    }
    game.gameOver(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (Random == 0) {
        game.setGameOverMessage(false, "0")
    } else if (Random == 1) {
        game.setGameOverMessage(false, "1")
    } else if (Random == 2) {
        game.setGameOverMessage(false, "2")
    } else if (Random == 3) {
        game.setGameOverMessage(false, "3")
    } else if (Random == 4) {
        game.setGameOverMessage(false, "4")
    } else if (Random == 5) {
        game.setGameOverMessage(false, "5")
    } else if (Random == 6) {
        game.setGameOverMessage(false, "6")
    } else if (Random == 7) {
        game.setGameOverMessage(false, "7")
    } else if (Random == 8) {
        game.setGameOverMessage(false, "8")
    } else if (Random == 9) {
        game.setGameOverMessage(false, "9")
    } else if (Random == 10) {
        game.setGameOverMessage(false, "10")
    }
    game.gameOver(false)
})
let projectile: Sprite = null
let Random = 0
game.showLongText("", DialogLayout.Full)
timer.after(30000, function () {
    Diffculty += 1
    timer.after(30000, function () {
        Diffculty += 1
    })
})
Random = randint(0, 10)
info.setScore(0)
scene.setBackgroundImage(assets.image`myImage`)
let Diffculty = 1
let Penguin = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . f . . . 
    . . . . . . . . . . . . f . f . 
    . . . . . . . . . . . f f f f . 
    . . . . . . . . . . f f f f f f 
    . . . f f f . f f f f f f f 1 f 
    . . f f f f f f f f f f f 1 1 f 
    . f f 1 1 f f f f f f f f 1 1 1 
    4 f 1 f 1 1 f 1 f f f f 1 1 1 1 
    . f 1 1 1 f f 1 1 1 1 1 1 1 1 4 
    . . f f f f f 1 1 1 1 1 1 1 1 4 
    . . . . . . . . 1 1 1 1 1 1 . 4 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(Penguin, 100, 100)
let Bottle_1 = sprites.create(assets.image`Bottle 1`, SpriteKind.Enemy)
let Bottle_2 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .....7977777777.....
    .....7777777777.....
    ......66666666......
    ......99999999......
    .....9999999999.....
    .....9999999999.....
    .....9999999999.....
    .....7777777777.....
    .....7777777777.....
    .....7777777776.....
    .....7777777776.....
    ......76666666......
    ....................
    ....................
    `, SpriteKind.Enemy)
let Bottle_3 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ........4eee........
    .......eeeeee.......
    .........cc.........
    .........4c.........
    ........4444........
    .......444444.......
    ......44444444......
    .....4444444444.....
    .....eeeeeeeeee.....
    .....eeeeeeeecc.....
    ......eeeeeecc......
    .......eccccc.......
    ....................
    ....................
    `, SpriteKind.Enemy)
let Bottle_4 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ........dd55........
    ........5555........
    .........44.........
    ........dddd........
    ........dddd........
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    .......dddddd.......
    ........dddd........
    ........4444........
    ....................
    `, SpriteKind.Enemy)
let Bottle_5 = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .........888........
    .........888........
    ......888888888.....
    ........fffff.......
    .......8888888......
    .......8998888......
    .......8988888......
    .......8888888......
    .......8888888......
    .......8888888......
    ......888888888.....
    ......fffffffff.....
    ....................
    ....................
    `, SpriteKind.Enemy)
Bottle_1.setPosition(randint(5, 160), 0)
Bottle_1.setVelocity(0, randint(1, 100))
Bottle_2.setPosition(randint(5, 160), 0)
Bottle_2.setVelocity(0, randint(50, 100))
Bottle_3.setPosition(randint(5, 160), 0)
Bottle_3.setVelocity(0, randint(50, 100))
Bottle_4.setVelocity(0, randint(50, 100))
Bottle_4.setPosition(randint(5, 160), 0)
Bottle_5.setVelocity(0, randint(50, 100))
Bottle_5.setPosition(randint(5, 160), 0)
game.onUpdateInterval(5000, function () {
    projectile = sprites.createProjectileFromSide(img`
        ..............fffcc.............
        ..............fcbddcc...........
        ...............fbbddcc..........
        ...............fcbbccf..........
        ..ccc.........ffccccccfffff.....
        ..cbbcc....fffcbbbbcbbbbbbbff...
        ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
        ...fbbdcfcccccbbbcbcbbffbbbbbbff
        ....fbbffcccccbbbbbcb1ff11bbbcbf
        ....fcbbcccccccbbbbb11111111bbbf
        ....fcccccccccccbbbb11cc33111bf.
        ...fcbbffbdbcccccbbb111c13cccf..
        ...fbbf..ccddddcfbbbc111c31cf...
        ..fbbf.....ccdccbbdbf111cccf....
        ..fff........ccbbdcfcccc........
        ..............fffff.............
        `, randint(50, 100) * Diffculty, 0)
    projectile.setPosition(0, Penguin.y)
    animation.runImageAnimation(
    projectile,
    [img`
        ..............fffcc.............
        ..............fcbddcc...........
        ...............fbbddcc..........
        ...............fcbbccf..........
        ..ccc.........ffccccccfffff.....
        ..cbbcc....fffcbbbbcbbbbbbbff...
        ...cbbdc.ffcccbbbbcbcbbbbbbbbf..
        ...fbbdcfcccccbbbcbcbbffbbbbbbff
        ....fbbffcccccbbbbbcb1ff11bbbcbf
        ....fcbbcccccccbbbbb11111111bbbf
        ....fcccccccccccbbbb11cc33111bf.
        ...fcbbffbdbcccccbbb111c13cccf..
        ...fbbf..ccddddcfbbbc111c31cf...
        ..fbbf.....ccdccbbdbf111cccf....
        ..fff........ccbbdcfcccc........
        ..............fffff.............
        `,img`
        ..............fffcc.............
        ..............fbbddc............
        ...............fbbddc...........
        ccc............fcbbccf..........
        cbbcc.........ffccccccffffff....
        .cbbdc.....fffcbbbbbbbbbbbbbff..
        .fbbddc..ffcccbbbbcbcbbbbbbbbbff
        ..fbbdfffcccccbbbcbcbbffbbbbbcbf
        ..fcbbbcccccccbbbcbcb1ff1111bbbf
        ..fccbcccccccccbbbbbb11111111bf.
        .fcbbfffccccccccbbbb11cc33cccf..
        .fbbf...cbdbcccccbbb111c131cf...
        fbbf.....ccdddddfbbbc111c33f....
        fff........ccddfbbdbf1111ff.....
        .............cfbbdbfccccc.......
        ..............fffff.............
        `,img`
        ..............fffc..............
        ..............fbddcc............
        ..ccc.........ffbddbc...........
        ..cbbc.........fcbbccf..........
        ...cbdc.......ffccccccfffffff...
        ...fbdc....fffcbbbbbbbbbbbbbcff.
        ....fbdc.ffcccbbbbbbcbbbbbbbbbcf
        ....fcdffcccccbbbcbcbbbffbbbbcbf
        ....fcbbccccccbbbcbcbbbff1111bbf
        ...fcbbccccccccbbbcbb11111111bf.
        ...fbbfffcccccccbbbb11bc33cccf..
        ..fbbf..cbdbcccccbbb111c131cf...
        ..fff....cbdddddccbbc111c33f....
        ..........ccbddccbbdf1111ff.....
        ............ccfbbbdfccccc.......
        ..............fffff.............
        `,img`
        ..............fffcc.............
        ..............fbbddc............
        ...............fbbddc...........
        ccc............fcbbccf..........
        cbbcc.........ffccccccffffff....
        .cbbdc.....fffcbbbbbbbbbbbbbff..
        .fbbddc..ffcccbbbbcbcbbbbbbbbbff
        ..fbbdfffcccccbbbcbcbbffbbbbbcbf
        ..fcbbbcccccccbbbcbcb1ff1111bbbf
        ..fccbcccccccccbbbbbb11111111bf.
        .fcbbfffccccccccbbbb11cc33cccf..
        .fbbf...cbdbcccccbbb111c131cf...
        fbbf.....ccdddddfbbbc111c33f....
        fff........ccddfbbdbf1111ff.....
        .............cfbbdbfccccc.......
        ..............fffff.............
        `],
    150,
    true
    )
})
forever(function () {
    if (Penguin.x > 160) {
        game.gameOver(false)
    }
    if (Penguin.y > 120) {
        game.gameOver(false)
    }
})
game.onUpdateInterval(100, function () {
    if (Bottle_1.y > 120) {
        Bottle_1.setPosition(randint(0, 160), 0)
        Bottle_1.setVelocity(0, randint(50, 100) * Diffculty)
        info.changeScoreBy(1)
    }
    if (Bottle_2.y > 120) {
        Bottle_2.setPosition(randint(0, 160), 0)
        Bottle_2.setVelocity(0, randint(50, 100) * Diffculty)
        info.changeScoreBy(1)
    }
    if (Bottle_3.y > 120) {
        Bottle_3.setPosition(randint(0, 160), 0)
        Bottle_3.setVelocity(0, randint(50, 100) * Diffculty)
        info.changeScoreBy(1)
    }
    if (Bottle_4.y > 120) {
        Bottle_4.setPosition(randint(0, 160), 0)
        Bottle_4.setVelocity(0, randint(50, 100) * Diffculty)
        info.changeScoreBy(1)
    }
    if (Bottle_5.y > 120) {
        Bottle_5.setPosition(randint(0, 160), 0)
        Bottle_5.setVelocity(0, randint(50, 100) * Diffculty)
        info.changeScoreBy(1)
    }
})
